CREATE INDEX medical_records_identity_number ON medical_records(patient_identity_number);
CREATE INDEX medical_records_user_id ON medical_records(created_by_user_id);
CREATE INDEX medical_records_created_at ON medical_records(created_at);
