// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KerakTelor86/GoBoiler/repos/auth (interfaces: AuthRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/KerakTelor86/GoBoiler/repos/auth"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// CreateStaff mocks base method.
func (m *MockAuthRepository) CreateStaff(arg0 context.Context, arg1 auth.Staff) (auth.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStaff", arg0, arg1)
	ret0, _ := ret[0].(auth.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStaff indicates an expected call of CreateStaff.
func (mr *MockAuthRepositoryMockRecorder) CreateStaff(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStaff", reflect.TypeOf((*MockAuthRepository)(nil).CreateStaff), arg0, arg1)
}

// FindStaffByPhone mocks base method.
func (m *MockAuthRepository) FindStaffByPhone(arg0 context.Context, arg1 string) (auth.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStaffByPhone", arg0, arg1)
	ret0, _ := ret[0].(auth.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStaffByPhone indicates an expected call of FindStaffByPhone.
func (mr *MockAuthRepositoryMockRecorder) FindStaffByPhone(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStaffByPhone", reflect.TypeOf((*MockAuthRepository)(nil).FindStaffByPhone), arg0, arg1)
}
